name: toddrhoades
favicon: null
layout_spectrum: 0.86542
typography_spectrum: 0.32841
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#000003'
    - '#7cc15a'
    - '#cfd1d1'
    - '#0166aa'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
